[package]
name = "aws-access-key-info"
version = "0.1.0"
edition = "2021"

[dependencies]
data-encoding = "2.5.0"
thiserror = "1.0"

[lib]
path = "src/lib.rs"

[[bin]]
name = "aws-access-key-info"
path = "src/main.rs"

[profile.release]
codegen-units = 1
lto = true
